name: Desktop Matrix Release (Release ID)

on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: "Release tag (optional, supports __VERSION__)"
        type: string
        default: ""
      release_name:
        description: "Release name (optional, supports __VERSION__)"
        type: string
        default: ""
      release_body:
        description: "Release body (optional)"
        type: string
        default: ""
      release_draft:
        description: "Create draft release"
        type: boolean
        default: false
      prerelease:
        description: "Mark as prerelease"
        type: boolean
        default: false
      args:
        description: "Extra args passed to the action"
        type: string
        default: ""

permissions:
  contents: write

# Multi-job example: create the release once and pass releaseId to each job to keep assets together.

jobs:
  desktop:
    name: Desktop (${{ matrix.name }})
    needs: create-release
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-22.04
            packager_formats: deb,appimage
            name: Linux
          - os: macos-14
            packager_formats: dmg
            name: macOS
          - os: windows-2022
            packager_formats: nsis
            name: Windows

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install Linux dependencies
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          sudo apt-get update
          sudo apt-get install libssl-dev pkg-config llvm clang libclang-dev binfmt-support libxcursor-dev libx11-dev libasound2-dev libpulse-dev libwayland-dev libxkbcommon-dev

      - name: Package (desktop)
        uses: Project-Robius-China/makepad-packaging-action@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          releaseId: ${{ needs.create-release.outputs.release_id }}
          args: ${{ inputs.args }}
          packager_formats: ${{ matrix.packager_formats }}

  create-release:
    name: Create Release
    runs-on: ubuntu-22.04
    env:
      RELEASE_TAG: ${{ inputs.release_tag != '' && inputs.release_tag || format('v{0}', github.run_id) }}
    outputs:
      release_id: ${{ steps.create_release.outputs.id }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.RELEASE_TAG }}
          name: ${{ inputs.release_name != '' && inputs.release_name || format('Makepad Release {0}', env.RELEASE_TAG) }}
          body: ${{ inputs.release_body }}
          draft: ${{ inputs.release_draft || false }}
          prerelease: ${{ inputs.prerelease || false }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
