name: iOS Device Build (TestFlight)

on:
  workflow_dispatch:
    inputs:
      ios_org:
        description: "iOS org (e.g. com.example)"
        type: string
        default: "com.example"
      ios_app:
        description: "iOS app name"
        type: string
        default: "ExampleApp"
      create_ipa:
        description: "Create IPA (true/false)"
        type: boolean
        default: true
      upload_testflight:
        description: "Upload to TestFlight (true/false)"
        type: boolean
        default: true
      args:
        description: "Extra args passed to the action"
        type: string
        default: ""

permissions:
  contents: write

jobs:
  ios:
    name: iOS
    runs-on: macos-14
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Package (iOS)
        uses: Project-Robius-China/makepad-packaging-action@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MAKEPAD_IOS_ORG: ${{ inputs.ios_org }}
          MAKEPAD_IOS_APP: ${{ inputs.ios_app }}
          MAKEPAD_IOS_CREATE_IPA: ${{ inputs.create_ipa }}
          MAKEPAD_IOS_UPLOAD_TESTFLIGHT: ${{ inputs.upload_testflight }}
          APPLE_CERTIFICATE: ${{ secrets.APPLE_CERTIFICATE }}
          APPLE_CERTIFICATE_PASSWORD: ${{ secrets.APPLE_CERTIFICATE_PASSWORD }}
          APPLE_PROVISIONING_PROFILE: ${{ secrets.APPLE_PROVISIONING_PROFILE }}
          APPLE_KEYCHAIN_PASSWORD: ${{ secrets.APPLE_KEYCHAIN_PASSWORD }}
          # Here we add the App Store Connect API credentials
          APP_STORE_CONNECT_API_KEY_CONTENT: ${{ secrets.APP_STORE_CONNECT_API_KEY_CONTENT }}
          APP_STORE_CONNECT_KEY_ID: ${{ secrets.APP_STORE_CONNECT_KEY_ID }}
          APP_STORE_CONNECT_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
        with:
          args: --target aarch64-apple-ios ${{ inputs.args }}
